/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace FhenixGovernance {
  export type MultiResolverPanelStruct = {
    marketId: BytesLike;
    resolver1: AddressLike;
    resolver2: AddressLike;
    resolver3: AddressLike;
    votesSubmitted: BigNumberish;
    outcomeVotes: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ];
    finalized: boolean;
    winningOutcome: BigNumberish;
    assignedAt: BigNumberish;
  };

  export type MultiResolverPanelStructOutput = [
    marketId: string,
    resolver1: string,
    resolver2: string,
    resolver3: string,
    votesSubmitted: bigint,
    outcomeVotes: [bigint, bigint, bigint, bigint, bigint],
    finalized: boolean,
    winningOutcome: bigint,
    assignedAt: bigint
  ] & {
    marketId: string;
    resolver1: string;
    resolver2: string;
    resolver3: string;
    votesSubmitted: bigint;
    outcomeVotes: [bigint, bigint, bigint, bigint, bigint];
    finalized: boolean;
    winningOutcome: bigint;
    assignedAt: bigint;
  };

  export type ProposalStruct = {
    id: BytesLike;
    proposer: AddressLike;
    proposalType: BigNumberish;
    target: BytesLike;
    payload1: BigNumberish;
    payload2: BytesLike;
    votesFor: BigNumberish;
    votesAgainst: BigNumberish;
    quorumRequired: BigNumberish;
    createdAt: BigNumberish;
    votingDeadline: BigNumberish;
    timelockUntil: BigNumberish;
    status: BigNumberish;
  };

  export type ProposalStructOutput = [
    id: string,
    proposer: string,
    proposalType: bigint,
    target: string,
    payload1: bigint,
    payload2: string,
    votesFor: bigint,
    votesAgainst: bigint,
    quorumRequired: bigint,
    createdAt: bigint,
    votingDeadline: bigint,
    timelockUntil: bigint,
    status: bigint
  ] & {
    id: string;
    proposer: string;
    proposalType: bigint;
    target: string;
    payload1: bigint;
    payload2: string;
    votesFor: bigint;
    votesAgainst: bigint;
    quorumRequired: bigint;
    createdAt: bigint;
    votingDeadline: bigint;
    timelockUntil: bigint;
    status: bigint;
  };

  export type ResolverProfileStruct = {
    resolver: AddressLike;
    stakeAmount: BigNumberish;
    tier: BigNumberish;
    marketsResolved: BigNumberish;
    disputesReceived: BigNumberish;
    disputesLost: BigNumberish;
    strikes: BigNumberish;
    reputationScore: BigNumberish;
    registeredAt: BigNumberish;
    lastActiveAt: BigNumberish;
    isActive: boolean;
  };

  export type ResolverProfileStructOutput = [
    resolver: string,
    stakeAmount: bigint,
    tier: bigint,
    marketsResolved: bigint,
    disputesReceived: bigint,
    disputesLost: bigint,
    strikes: bigint,
    reputationScore: bigint,
    registeredAt: bigint,
    lastActiveAt: bigint,
    isActive: boolean
  ] & {
    resolver: string;
    stakeAmount: bigint;
    tier: bigint;
    marketsResolved: bigint;
    disputesReceived: bigint;
    disputesLost: bigint;
    strikes: bigint;
    reputationScore: bigint;
    registeredAt: bigint;
    lastActiveAt: bigint;
    isActive: boolean;
  };
}

export interface FhenixGovernanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ESCALATION_BOND"
      | "ESCALATION_COMMUNITY"
      | "ESCALATION_INITIATED"
      | "ESCALATION_NONE"
      | "ESCALATION_RESOLVED"
      | "ESCALATION_WINDOW"
      | "GOLD_MARKETS_REQUIRED"
      | "GOLD_REPUTATION_MIN"
      | "MAX_STRIKES"
      | "MIN_PROPOSAL_STAKE"
      | "MIN_VOTE_AMOUNT"
      | "PANEL_MAJORITY"
      | "PANEL_SIZE"
      | "PROPOSAL_EMERGENCY_PAUSE"
      | "PROPOSAL_FEE_CHANGE"
      | "PROPOSAL_PARAMETER"
      | "PROPOSAL_RESOLVER_ELECTION"
      | "PROPOSAL_RESOLVE_DISPUTE"
      | "PROPOSAL_TREASURY"
      | "QUORUM_EMERGENCY"
      | "QUORUM_FEE"
      | "QUORUM_PARAMETER"
      | "QUORUM_RESOLVE"
      | "QUORUM_RESOLVER"
      | "QUORUM_TREASURY"
      | "RESOLVER_STAKE_BRONZE"
      | "SILVER_MARKETS_REQUIRED"
      | "SILVER_REPUTATION_MIN"
      | "SLASH_PERCENT_MAJOR"
      | "SLASH_PERCENT_MINOR"
      | "STATUS_ACTIVE"
      | "STATUS_EXECUTED"
      | "STATUS_PASSED"
      | "STATUS_REJECTED"
      | "STATUS_VETOED"
      | "TIER_BRONZE"
      | "TIER_COMMITTEE"
      | "TIER_GOLD"
      | "TIER_SILVER"
      | "TIMELOCK_LONG"
      | "TIMELOCK_STANDARD"
      | "VOTING_PERIOD"
      | "approvedResolvers"
      | "assignResolverPanel"
      | "blacklistResolver"
      | "blacklistedResolvers"
      | "claimReward"
      | "committeeDecision"
      | "committeeFinalized"
      | "committeeMembers"
      | "committeeOutcomeVotes"
      | "committeeSize"
      | "committeeVoteResolve"
      | "committeeVoted"
      | "createProposal"
      | "currentEpochId"
      | "decryptionRequested"
      | "delegateVotes"
      | "deployer"
      | "depositProtocolFees"
      | "escalateToCommunity"
      | "escalations"
      | "executeGovernance"
      | "finalizeCommitteeVote"
      | "finalizeEscalation"
      | "finalizeVote"
      | "fundRewardEpoch"
      | "getPanel"
      | "getProposal"
      | "getResolverProfile"
      | "governanceParams"
      | "governancePaused"
      | "governanceResolve"
      | "governanceResolvedOutcomes"
      | "guardians"
      | "initGovernance"
      | "initialized"
      | "initiateEscalation"
      | "marketsContract"
      | "panelVote"
      | "panelVoted"
      | "proposalCount"
      | "proposals"
      | "recordContribution"
      | "registerResolver"
      | "requestVoteDecryption"
      | "resolverPanels"
      | "resolverRegistry"
      | "revealProposalTally"
      | "rewardEpochs"
      | "setCommitteeMembers"
      | "slashResolver"
      | "treasuryBalance"
      | "undelegateVotes"
      | "unlockAfterVote"
      | "unstakeResolver"
      | "updateResolverStats"
      | "upgradeResolverTier"
      | "vetoProposal"
      | "voteAgainst"
      | "voteEscalation"
      | "voteFor"
      | "withdrawEscalationBond"
      | "withdrawTreasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DelegationCreated"
      | "DelegationRemoved"
      | "EscalatedToCommunity"
      | "EscalationInitiated"
      | "EscalationResolved"
      | "EscalationVoteCast"
      | "GovernanceInitialized"
      | "PanelAssigned"
      | "PanelFinalized"
      | "PanelVoteSubmitted"
      | "ProposalCreated"
      | "ProposalDecryptionRequested"
      | "ProposalExecuted"
      | "ProposalVetoed"
      | "ResolverBlacklisted"
      | "ResolverRegistered"
      | "ResolverSlashed"
      | "ResolverTierUpgraded"
      | "ResolverUnstaked"
      | "RewardClaimed"
      | "RewardEpochFunded"
      | "VoteCast"
      | "VoteFinalized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ESCALATION_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ESCALATION_COMMUNITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ESCALATION_INITIATED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ESCALATION_NONE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ESCALATION_RESOLVED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ESCALATION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOLD_MARKETS_REQUIRED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOLD_REPUTATION_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STRIKES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PROPOSAL_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PANEL_MAJORITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PANEL_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_EMERGENCY_PAUSE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_FEE_CHANGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_PARAMETER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_RESOLVER_ELECTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_RESOLVE_DISPUTE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_TREASURY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_EMERGENCY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_PARAMETER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_RESOLVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_RESOLVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "QUORUM_TREASURY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESOLVER_STAKE_BRONZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SILVER_MARKETS_REQUIRED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SILVER_REPUTATION_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_PERCENT_MAJOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_PERCENT_MINOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_ACTIVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_EXECUTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_PASSED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_REJECTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_VETOED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_BRONZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_COMMITTEE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TIER_GOLD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER_SILVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_LONG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_STANDARD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approvedResolvers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignResolverPanel",
    values: [BytesLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistedResolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeDecision",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeFinalized",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeMembers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeOutcomeVotes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "committeeVoteResolve",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "committeeVoted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentEpochId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequested",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositProtocolFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escalateToCommunity",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "escalations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeGovernance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeCommitteeVote",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeEscalation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeVote",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundRewardEpoch",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPanel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolverProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceParams",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governancePaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceResolve",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceResolvedOutcomes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "guardians", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initGovernance",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateEscalation",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketsContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "panelVote",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "panelVoted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordContribution",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerResolver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestVoteDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolverPanels",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolverRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealProposalTally",
    values: [BytesLike, boolean, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewardEpochs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommitteeMembers",
    values: [
      [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "slashResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockAfterVote",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeResolver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateResolverStats",
    values: [AddressLike, boolean, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeResolverTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vetoProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteAgainst",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteEscalation",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "voteFor", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "withdrawEscalationBond",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTreasury",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ESCALATION_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ESCALATION_COMMUNITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ESCALATION_INITIATED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ESCALATION_NONE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ESCALATION_RESOLVED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ESCALATION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOLD_MARKETS_REQUIRED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOLD_REPUTATION_MIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STRIKES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PROPOSAL_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOTE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PANEL_MAJORITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PANEL_SIZE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_EMERGENCY_PAUSE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_FEE_CHANGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_PARAMETER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_RESOLVER_ELECTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_RESOLVE_DISPUTE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_TREASURY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_EMERGENCY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "QUORUM_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_PARAMETER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_RESOLVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_RESOLVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "QUORUM_TREASURY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESOLVER_STAKE_BRONZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SILVER_MARKETS_REQUIRED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SILVER_REPUTATION_MIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_PERCENT_MAJOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_PERCENT_MINOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_ACTIVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_EXECUTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_PASSED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_REJECTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_VETOED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_BRONZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_COMMITTEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TIER_GOLD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TIER_SILVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_LONG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_STANDARD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedResolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignResolverPanel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistedResolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeOutcomeVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeVoteResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "committeeVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentEpochId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositProtocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escalateToCommunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escalations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeCommitteeVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeEscalation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundRewardEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPanel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolverProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governancePaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceResolvedOutcomes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guardians", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateEscalation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "panelVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "panelVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestVoteDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolverPanels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolverRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealProposalTally",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardEpochs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCommitteeMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegateVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockAfterVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateResolverStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeResolverTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vetoProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteAgainst",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteEscalation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEscalationBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTreasury",
    data: BytesLike
  ): Result;
}

export namespace DelegationCreatedEvent {
  export type InputTuple = [delegator: AddressLike, delegate: AddressLike];
  export type OutputTuple = [delegator: string, delegate: string];
  export interface OutputObject {
    delegator: string;
    delegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegationRemovedEvent {
  export type InputTuple = [delegator: AddressLike, delegate: AddressLike];
  export type OutputTuple = [delegator: string, delegate: string];
  export interface OutputObject {
    delegator: string;
    delegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscalatedToCommunityEvent {
  export type InputTuple = [marketId: BytesLike];
  export type OutputTuple = [marketId: string];
  export interface OutputObject {
    marketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscalationInitiatedEvent {
  export type InputTuple = [marketId: BytesLike, initiator: AddressLike];
  export type OutputTuple = [marketId: string, initiator: string];
  export interface OutputObject {
    marketId: string;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscalationResolvedEvent {
  export type InputTuple = [marketId: BytesLike];
  export type OutputTuple = [marketId: string];
  export interface OutputObject {
    marketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscalationVoteCastEvent {
  export type InputTuple = [marketId: BytesLike, voter: AddressLike];
  export type OutputTuple = [marketId: string, voter: string];
  export interface OutputObject {
    marketId: string;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceInitializedEvent {
  export type InputTuple = [
    guardian1: AddressLike,
    guardian2: AddressLike,
    guardian3: AddressLike
  ];
  export type OutputTuple = [
    guardian1: string,
    guardian2: string,
    guardian3: string
  ];
  export interface OutputObject {
    guardian1: string;
    guardian2: string;
    guardian3: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PanelAssignedEvent {
  export type InputTuple = [marketId: BytesLike];
  export type OutputTuple = [marketId: string];
  export interface OutputObject {
    marketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PanelFinalizedEvent {
  export type InputTuple = [marketId: BytesLike];
  export type OutputTuple = [marketId: string];
  export interface OutputObject {
    marketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PanelVoteSubmittedEvent {
  export type InputTuple = [marketId: BytesLike, resolver: AddressLike];
  export type OutputTuple = [marketId: string, resolver: string];
  export interface OutputObject {
    marketId: string;
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    proposer: AddressLike,
    proposalType: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    proposer: string,
    proposalType: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    proposer: string;
    proposalType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalDecryptionRequestedEvent {
  export type InputTuple = [proposalId: BytesLike];
  export type OutputTuple = [proposalId: string];
  export interface OutputObject {
    proposalId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BytesLike];
  export type OutputTuple = [proposalId: string];
  export interface OutputObject {
    proposalId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalVetoedEvent {
  export type InputTuple = [proposalId: BytesLike];
  export type OutputTuple = [proposalId: string];
  export interface OutputObject {
    proposalId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverBlacklistedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverRegisteredEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverSlashedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverTierUpgradedEvent {
  export type InputTuple = [resolver: AddressLike, newTier: BigNumberish];
  export type OutputTuple = [resolver: string, newTier: bigint];
  export interface OutputObject {
    resolver: string;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverUnstakedEvent {
  export type InputTuple = [resolver: AddressLike];
  export type OutputTuple = [resolver: string];
  export interface OutputObject {
    resolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardEpochFundedEvent {
  export type InputTuple = [epochId: BigNumberish];
  export type OutputTuple = [epochId: bigint];
  export interface OutputObject {
    epochId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [proposalId: BytesLike, voter: AddressLike];
  export type OutputTuple = [proposalId: string, voter: string];
  export interface OutputObject {
    proposalId: string;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteFinalizedEvent {
  export type InputTuple = [proposalId: BytesLike, status: BigNumberish];
  export type OutputTuple = [proposalId: string, status: bigint];
  export interface OutputObject {
    proposalId: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FhenixGovernance extends BaseContract {
  connect(runner?: ContractRunner | null): FhenixGovernance;
  waitForDeployment(): Promise<this>;

  interface: FhenixGovernanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ESCALATION_BOND: TypedContractMethod<[], [bigint], "view">;

  ESCALATION_COMMUNITY: TypedContractMethod<[], [bigint], "view">;

  ESCALATION_INITIATED: TypedContractMethod<[], [bigint], "view">;

  ESCALATION_NONE: TypedContractMethod<[], [bigint], "view">;

  ESCALATION_RESOLVED: TypedContractMethod<[], [bigint], "view">;

  ESCALATION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  GOLD_MARKETS_REQUIRED: TypedContractMethod<[], [bigint], "view">;

  GOLD_REPUTATION_MIN: TypedContractMethod<[], [bigint], "view">;

  MAX_STRIKES: TypedContractMethod<[], [bigint], "view">;

  MIN_PROPOSAL_STAKE: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  PANEL_MAJORITY: TypedContractMethod<[], [bigint], "view">;

  PANEL_SIZE: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_EMERGENCY_PAUSE: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_FEE_CHANGE: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_PARAMETER: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_RESOLVER_ELECTION: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_RESOLVE_DISPUTE: TypedContractMethod<[], [bigint], "view">;

  PROPOSAL_TREASURY: TypedContractMethod<[], [bigint], "view">;

  QUORUM_EMERGENCY: TypedContractMethod<[], [bigint], "view">;

  QUORUM_FEE: TypedContractMethod<[], [bigint], "view">;

  QUORUM_PARAMETER: TypedContractMethod<[], [bigint], "view">;

  QUORUM_RESOLVE: TypedContractMethod<[], [bigint], "view">;

  QUORUM_RESOLVER: TypedContractMethod<[], [bigint], "view">;

  QUORUM_TREASURY: TypedContractMethod<[], [bigint], "view">;

  RESOLVER_STAKE_BRONZE: TypedContractMethod<[], [bigint], "view">;

  SILVER_MARKETS_REQUIRED: TypedContractMethod<[], [bigint], "view">;

  SILVER_REPUTATION_MIN: TypedContractMethod<[], [bigint], "view">;

  SLASH_PERCENT_MAJOR: TypedContractMethod<[], [bigint], "view">;

  SLASH_PERCENT_MINOR: TypedContractMethod<[], [bigint], "view">;

  STATUS_ACTIVE: TypedContractMethod<[], [bigint], "view">;

  STATUS_EXECUTED: TypedContractMethod<[], [bigint], "view">;

  STATUS_PASSED: TypedContractMethod<[], [bigint], "view">;

  STATUS_REJECTED: TypedContractMethod<[], [bigint], "view">;

  STATUS_VETOED: TypedContractMethod<[], [bigint], "view">;

  TIER_BRONZE: TypedContractMethod<[], [bigint], "view">;

  TIER_COMMITTEE: TypedContractMethod<[], [bigint], "view">;

  TIER_GOLD: TypedContractMethod<[], [bigint], "view">;

  TIER_SILVER: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK_LONG: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK_STANDARD: TypedContractMethod<[], [bigint], "view">;

  VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  approvedResolvers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  assignResolverPanel: TypedContractMethod<
    [marketId: BytesLike, r1: AddressLike, r2: AddressLike, r3: AddressLike],
    [void],
    "nonpayable"
  >;

  blacklistResolver: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  blacklistedResolvers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  claimReward: TypedContractMethod<
    [epochId: BigNumberish],
    [void],
    "nonpayable"
  >;

  committeeDecision: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  committeeFinalized: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  committeeMembers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  committeeOutcomeVotes: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  committeeSize: TypedContractMethod<[], [bigint], "view">;

  committeeVoteResolve: TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  committeeVoted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  createProposal: TypedContractMethod<
    [
      proposalType: BigNumberish,
      target: BytesLike,
      payload1: BigNumberish,
      payload2: BytesLike
    ],
    [string],
    "payable"
  >;

  currentEpochId: TypedContractMethod<[], [bigint], "view">;

  decryptionRequested: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  delegateVotes: TypedContractMethod<
    [delegate: AddressLike],
    [void],
    "payable"
  >;

  deployer: TypedContractMethod<[], [string], "view">;

  depositProtocolFees: TypedContractMethod<[], [void], "payable">;

  escalateToCommunity: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  escalations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        marketId: string;
        initiator: string;
        proposedOutcome: bigint;
        status: bigint;
        initiatedAt: bigint;
        bondAmount: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        communityDeadline: bigint;
      }
    ],
    "view"
  >;

  executeGovernance: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeCommitteeVote: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeEscalation: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeVote: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  fundRewardEpoch: TypedContractMethod<
    [lpReward: BigNumberish, traderReward: BigNumberish],
    [void],
    "payable"
  >;

  getPanel: TypedContractMethod<
    [marketId: BytesLike],
    [FhenixGovernance.MultiResolverPanelStructOutput],
    "view"
  >;

  getProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [FhenixGovernance.ProposalStructOutput],
    "view"
  >;

  getResolverProfile: TypedContractMethod<
    [resolver: AddressLike],
    [FhenixGovernance.ResolverProfileStructOutput],
    "view"
  >;

  governanceParams: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  governancePaused: TypedContractMethod<[], [boolean], "view">;

  governanceResolve: TypedContractMethod<
    [marketId: BytesLike, winningOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  governanceResolvedOutcomes: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  guardians: TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        guardian1: string;
        guardian2: string;
        guardian3: string;
        threshold: bigint;
      }
    ],
    "view"
  >;

  initGovernance: TypedContractMethod<
    [
      guardian1: AddressLike,
      guardian2: AddressLike,
      guardian3: AddressLike,
      _marketsContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initialized: TypedContractMethod<[], [boolean], "view">;

  initiateEscalation: TypedContractMethod<
    [marketId: BytesLike, proposedOutcome: BigNumberish],
    [void],
    "payable"
  >;

  marketsContract: TypedContractMethod<[], [string], "view">;

  panelVote: TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  panelVoted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        proposer: string;
        proposalType: bigint;
        target: string;
        payload1: bigint;
        payload2: string;
        votesFor: bigint;
        votesAgainst: bigint;
        quorumRequired: bigint;
        createdAt: bigint;
        votingDeadline: bigint;
        timelockUntil: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  recordContribution: TypedContractMethod<
    [
      user: AddressLike,
      epochId: BigNumberish,
      lpContribution: BigNumberish,
      tradeVolume: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerResolver: TypedContractMethod<[], [void], "payable">;

  requestVoteDecryption: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  resolverPanels: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean, bigint, bigint] & {
        marketId: string;
        resolver1: string;
        resolver2: string;
        resolver3: string;
        votesSubmitted: bigint;
        finalized: boolean;
        winningOutcome: bigint;
        assignedAt: bigint;
      }
    ],
    "view"
  >;

  resolverRegistry: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        resolver: string;
        stakeAmount: bigint;
        tier: bigint;
        marketsResolved: bigint;
        disputesReceived: bigint;
        disputesLost: bigint;
        strikes: bigint;
        reputationScore: bigint;
        registeredAt: bigint;
        lastActiveAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  revealProposalTally: TypedContractMethod<
    [
      proposalId: BytesLike,
      isFor: boolean,
      plaintext: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  rewardEpochs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        epochId: bigint;
        totalLPReward: bigint;
        totalTraderReward: bigint;
        totalLPContributions: bigint;
        totalTradeVolume: bigint;
        startedAt: bigint;
        distributed: boolean;
      }
    ],
    "view"
  >;

  setCommitteeMembers: TypedContractMethod<
    [
      members: [
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike
      ],
      size: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  slashResolver: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryBalance: TypedContractMethod<[], [bigint], "view">;

  undelegateVotes: TypedContractMethod<
    [delegate: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockAfterVote: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  unstakeResolver: TypedContractMethod<[], [void], "nonpayable">;

  updateResolverStats: TypedContractMethod<
    [
      resolver: AddressLike,
      resolved: boolean,
      disputed: boolean,
      disputeLost: boolean
    ],
    [void],
    "nonpayable"
  >;

  upgradeResolverTier: TypedContractMethod<
    [resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  vetoProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  voteAgainst: TypedContractMethod<[proposalId: BytesLike], [void], "payable">;

  voteEscalation: TypedContractMethod<
    [marketId: BytesLike, support: boolean],
    [void],
    "payable"
  >;

  voteFor: TypedContractMethod<[proposalId: BytesLike], [void], "payable">;

  withdrawEscalationBond: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawTreasury: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ESCALATION_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ESCALATION_COMMUNITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ESCALATION_INITIATED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ESCALATION_NONE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ESCALATION_RESOLVED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ESCALATION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOLD_MARKETS_REQUIRED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOLD_REPUTATION_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STRIKES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PROPOSAL_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PANEL_MAJORITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PANEL_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_EMERGENCY_PAUSE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_FEE_CHANGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_PARAMETER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_RESOLVER_ELECTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_RESOLVE_DISPUTE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_TREASURY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_EMERGENCY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_PARAMETER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_RESOLVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_RESOLVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "QUORUM_TREASURY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESOLVER_STAKE_BRONZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SILVER_MARKETS_REQUIRED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SILVER_REPUTATION_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_PERCENT_MAJOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_PERCENT_MINOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_ACTIVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_EXECUTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_PASSED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_REJECTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_VETOED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_BRONZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_COMMITTEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_GOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_SILVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_LONG"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_STANDARD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approvedResolvers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "assignResolverPanel"
  ): TypedContractMethod<
    [marketId: BytesLike, r1: AddressLike, r2: AddressLike, r3: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklistResolver"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blacklistedResolvers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[epochId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "committeeDecision"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "committeeFinalized"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "committeeMembers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "committeeOutcomeVotes"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "committeeSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "committeeVoteResolve"
  ): TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "committeeVoted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      proposalType: BigNumberish,
      target: BytesLike,
      payload1: BigNumberish,
      payload2: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "currentEpochId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decryptionRequested"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "delegateVotes"
  ): TypedContractMethod<[delegate: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "deployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositProtocolFees"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "escalateToCommunity"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escalations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        marketId: string;
        initiator: string;
        proposedOutcome: bigint;
        status: bigint;
        initiatedAt: bigint;
        bondAmount: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        communityDeadline: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeGovernance"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeCommitteeVote"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeEscalation"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeVote"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundRewardEpoch"
  ): TypedContractMethod<
    [lpReward: BigNumberish, traderReward: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getPanel"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [FhenixGovernance.MultiResolverPanelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [FhenixGovernance.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResolverProfile"
  ): TypedContractMethod<
    [resolver: AddressLike],
    [FhenixGovernance.ResolverProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "governanceParams"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "governancePaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "governanceResolve"
  ): TypedContractMethod<
    [marketId: BytesLike, winningOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "governanceResolvedOutcomes"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "guardians"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        guardian1: string;
        guardian2: string;
        guardian3: string;
        threshold: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initGovernance"
  ): TypedContractMethod<
    [
      guardian1: AddressLike,
      guardian2: AddressLike,
      guardian3: AddressLike,
      _marketsContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "initiateEscalation"
  ): TypedContractMethod<
    [marketId: BytesLike, proposedOutcome: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "marketsContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "panelVote"
  ): TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "panelVoted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        proposer: string;
        proposalType: bigint;
        target: string;
        payload1: bigint;
        payload2: string;
        votesFor: bigint;
        votesAgainst: bigint;
        quorumRequired: bigint;
        createdAt: bigint;
        votingDeadline: bigint;
        timelockUntil: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordContribution"
  ): TypedContractMethod<
    [
      user: AddressLike,
      epochId: BigNumberish,
      lpContribution: BigNumberish,
      tradeVolume: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerResolver"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "requestVoteDecryption"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolverPanels"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean, bigint, bigint] & {
        marketId: string;
        resolver1: string;
        resolver2: string;
        resolver3: string;
        votesSubmitted: bigint;
        finalized: boolean;
        winningOutcome: bigint;
        assignedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolverRegistry"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        resolver: string;
        stakeAmount: bigint;
        tier: bigint;
        marketsResolved: bigint;
        disputesReceived: bigint;
        disputesLost: bigint;
        strikes: bigint;
        reputationScore: bigint;
        registeredAt: bigint;
        lastActiveAt: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealProposalTally"
  ): TypedContractMethod<
    [
      proposalId: BytesLike,
      isFor: boolean,
      plaintext: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rewardEpochs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        epochId: bigint;
        totalLPReward: bigint;
        totalTraderReward: bigint;
        totalLPContributions: bigint;
        totalTradeVolume: bigint;
        startedAt: bigint;
        distributed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCommitteeMembers"
  ): TypedContractMethod<
    [
      members: [
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike,
        AddressLike
      ],
      size: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashResolver"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "undelegateVotes"
  ): TypedContractMethod<[delegate: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockAfterVote"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeResolver"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateResolverStats"
  ): TypedContractMethod<
    [
      resolver: AddressLike,
      resolved: boolean,
      disputed: boolean,
      disputeLost: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeResolverTier"
  ): TypedContractMethod<[resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vetoProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteAgainst"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "voteEscalation"
  ): TypedContractMethod<
    [marketId: BytesLike, support: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "voteFor"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "withdrawEscalationBond"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawTreasury"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DelegationCreated"
  ): TypedContractEvent<
    DelegationCreatedEvent.InputTuple,
    DelegationCreatedEvent.OutputTuple,
    DelegationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DelegationRemoved"
  ): TypedContractEvent<
    DelegationRemovedEvent.InputTuple,
    DelegationRemovedEvent.OutputTuple,
    DelegationRemovedEvent.OutputObject
  >;
  getEvent(
    key: "EscalatedToCommunity"
  ): TypedContractEvent<
    EscalatedToCommunityEvent.InputTuple,
    EscalatedToCommunityEvent.OutputTuple,
    EscalatedToCommunityEvent.OutputObject
  >;
  getEvent(
    key: "EscalationInitiated"
  ): TypedContractEvent<
    EscalationInitiatedEvent.InputTuple,
    EscalationInitiatedEvent.OutputTuple,
    EscalationInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "EscalationResolved"
  ): TypedContractEvent<
    EscalationResolvedEvent.InputTuple,
    EscalationResolvedEvent.OutputTuple,
    EscalationResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscalationVoteCast"
  ): TypedContractEvent<
    EscalationVoteCastEvent.InputTuple,
    EscalationVoteCastEvent.OutputTuple,
    EscalationVoteCastEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceInitialized"
  ): TypedContractEvent<
    GovernanceInitializedEvent.InputTuple,
    GovernanceInitializedEvent.OutputTuple,
    GovernanceInitializedEvent.OutputObject
  >;
  getEvent(
    key: "PanelAssigned"
  ): TypedContractEvent<
    PanelAssignedEvent.InputTuple,
    PanelAssignedEvent.OutputTuple,
    PanelAssignedEvent.OutputObject
  >;
  getEvent(
    key: "PanelFinalized"
  ): TypedContractEvent<
    PanelFinalizedEvent.InputTuple,
    PanelFinalizedEvent.OutputTuple,
    PanelFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "PanelVoteSubmitted"
  ): TypedContractEvent<
    PanelVoteSubmittedEvent.InputTuple,
    PanelVoteSubmittedEvent.OutputTuple,
    PanelVoteSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalDecryptionRequested"
  ): TypedContractEvent<
    ProposalDecryptionRequestedEvent.InputTuple,
    ProposalDecryptionRequestedEvent.OutputTuple,
    ProposalDecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalVetoed"
  ): TypedContractEvent<
    ProposalVetoedEvent.InputTuple,
    ProposalVetoedEvent.OutputTuple,
    ProposalVetoedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverBlacklisted"
  ): TypedContractEvent<
    ResolverBlacklistedEvent.InputTuple,
    ResolverBlacklistedEvent.OutputTuple,
    ResolverBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverRegistered"
  ): TypedContractEvent<
    ResolverRegisteredEvent.InputTuple,
    ResolverRegisteredEvent.OutputTuple,
    ResolverRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ResolverSlashed"
  ): TypedContractEvent<
    ResolverSlashedEvent.InputTuple,
    ResolverSlashedEvent.OutputTuple,
    ResolverSlashedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverTierUpgraded"
  ): TypedContractEvent<
    ResolverTierUpgradedEvent.InputTuple,
    ResolverTierUpgradedEvent.OutputTuple,
    ResolverTierUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverUnstaked"
  ): TypedContractEvent<
    ResolverUnstakedEvent.InputTuple,
    ResolverUnstakedEvent.OutputTuple,
    ResolverUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardEpochFunded"
  ): TypedContractEvent<
    RewardEpochFundedEvent.InputTuple,
    RewardEpochFundedEvent.OutputTuple,
    RewardEpochFundedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoteFinalized"
  ): TypedContractEvent<
    VoteFinalizedEvent.InputTuple,
    VoteFinalizedEvent.OutputTuple,
    VoteFinalizedEvent.OutputObject
  >;

  filters: {
    "DelegationCreated(address,address)": TypedContractEvent<
      DelegationCreatedEvent.InputTuple,
      DelegationCreatedEvent.OutputTuple,
      DelegationCreatedEvent.OutputObject
    >;
    DelegationCreated: TypedContractEvent<
      DelegationCreatedEvent.InputTuple,
      DelegationCreatedEvent.OutputTuple,
      DelegationCreatedEvent.OutputObject
    >;

    "DelegationRemoved(address,address)": TypedContractEvent<
      DelegationRemovedEvent.InputTuple,
      DelegationRemovedEvent.OutputTuple,
      DelegationRemovedEvent.OutputObject
    >;
    DelegationRemoved: TypedContractEvent<
      DelegationRemovedEvent.InputTuple,
      DelegationRemovedEvent.OutputTuple,
      DelegationRemovedEvent.OutputObject
    >;

    "EscalatedToCommunity(bytes32)": TypedContractEvent<
      EscalatedToCommunityEvent.InputTuple,
      EscalatedToCommunityEvent.OutputTuple,
      EscalatedToCommunityEvent.OutputObject
    >;
    EscalatedToCommunity: TypedContractEvent<
      EscalatedToCommunityEvent.InputTuple,
      EscalatedToCommunityEvent.OutputTuple,
      EscalatedToCommunityEvent.OutputObject
    >;

    "EscalationInitiated(bytes32,address)": TypedContractEvent<
      EscalationInitiatedEvent.InputTuple,
      EscalationInitiatedEvent.OutputTuple,
      EscalationInitiatedEvent.OutputObject
    >;
    EscalationInitiated: TypedContractEvent<
      EscalationInitiatedEvent.InputTuple,
      EscalationInitiatedEvent.OutputTuple,
      EscalationInitiatedEvent.OutputObject
    >;

    "EscalationResolved(bytes32)": TypedContractEvent<
      EscalationResolvedEvent.InputTuple,
      EscalationResolvedEvent.OutputTuple,
      EscalationResolvedEvent.OutputObject
    >;
    EscalationResolved: TypedContractEvent<
      EscalationResolvedEvent.InputTuple,
      EscalationResolvedEvent.OutputTuple,
      EscalationResolvedEvent.OutputObject
    >;

    "EscalationVoteCast(bytes32,address)": TypedContractEvent<
      EscalationVoteCastEvent.InputTuple,
      EscalationVoteCastEvent.OutputTuple,
      EscalationVoteCastEvent.OutputObject
    >;
    EscalationVoteCast: TypedContractEvent<
      EscalationVoteCastEvent.InputTuple,
      EscalationVoteCastEvent.OutputTuple,
      EscalationVoteCastEvent.OutputObject
    >;

    "GovernanceInitialized(address,address,address)": TypedContractEvent<
      GovernanceInitializedEvent.InputTuple,
      GovernanceInitializedEvent.OutputTuple,
      GovernanceInitializedEvent.OutputObject
    >;
    GovernanceInitialized: TypedContractEvent<
      GovernanceInitializedEvent.InputTuple,
      GovernanceInitializedEvent.OutputTuple,
      GovernanceInitializedEvent.OutputObject
    >;

    "PanelAssigned(bytes32)": TypedContractEvent<
      PanelAssignedEvent.InputTuple,
      PanelAssignedEvent.OutputTuple,
      PanelAssignedEvent.OutputObject
    >;
    PanelAssigned: TypedContractEvent<
      PanelAssignedEvent.InputTuple,
      PanelAssignedEvent.OutputTuple,
      PanelAssignedEvent.OutputObject
    >;

    "PanelFinalized(bytes32)": TypedContractEvent<
      PanelFinalizedEvent.InputTuple,
      PanelFinalizedEvent.OutputTuple,
      PanelFinalizedEvent.OutputObject
    >;
    PanelFinalized: TypedContractEvent<
      PanelFinalizedEvent.InputTuple,
      PanelFinalizedEvent.OutputTuple,
      PanelFinalizedEvent.OutputObject
    >;

    "PanelVoteSubmitted(bytes32,address)": TypedContractEvent<
      PanelVoteSubmittedEvent.InputTuple,
      PanelVoteSubmittedEvent.OutputTuple,
      PanelVoteSubmittedEvent.OutputObject
    >;
    PanelVoteSubmitted: TypedContractEvent<
      PanelVoteSubmittedEvent.InputTuple,
      PanelVoteSubmittedEvent.OutputTuple,
      PanelVoteSubmittedEvent.OutputObject
    >;

    "ProposalCreated(bytes32,address,uint8)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalDecryptionRequested(bytes32)": TypedContractEvent<
      ProposalDecryptionRequestedEvent.InputTuple,
      ProposalDecryptionRequestedEvent.OutputTuple,
      ProposalDecryptionRequestedEvent.OutputObject
    >;
    ProposalDecryptionRequested: TypedContractEvent<
      ProposalDecryptionRequestedEvent.InputTuple,
      ProposalDecryptionRequestedEvent.OutputTuple,
      ProposalDecryptionRequestedEvent.OutputObject
    >;

    "ProposalExecuted(bytes32)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalVetoed(bytes32)": TypedContractEvent<
      ProposalVetoedEvent.InputTuple,
      ProposalVetoedEvent.OutputTuple,
      ProposalVetoedEvent.OutputObject
    >;
    ProposalVetoed: TypedContractEvent<
      ProposalVetoedEvent.InputTuple,
      ProposalVetoedEvent.OutputTuple,
      ProposalVetoedEvent.OutputObject
    >;

    "ResolverBlacklisted(address)": TypedContractEvent<
      ResolverBlacklistedEvent.InputTuple,
      ResolverBlacklistedEvent.OutputTuple,
      ResolverBlacklistedEvent.OutputObject
    >;
    ResolverBlacklisted: TypedContractEvent<
      ResolverBlacklistedEvent.InputTuple,
      ResolverBlacklistedEvent.OutputTuple,
      ResolverBlacklistedEvent.OutputObject
    >;

    "ResolverRegistered(address)": TypedContractEvent<
      ResolverRegisteredEvent.InputTuple,
      ResolverRegisteredEvent.OutputTuple,
      ResolverRegisteredEvent.OutputObject
    >;
    ResolverRegistered: TypedContractEvent<
      ResolverRegisteredEvent.InputTuple,
      ResolverRegisteredEvent.OutputTuple,
      ResolverRegisteredEvent.OutputObject
    >;

    "ResolverSlashed(address)": TypedContractEvent<
      ResolverSlashedEvent.InputTuple,
      ResolverSlashedEvent.OutputTuple,
      ResolverSlashedEvent.OutputObject
    >;
    ResolverSlashed: TypedContractEvent<
      ResolverSlashedEvent.InputTuple,
      ResolverSlashedEvent.OutputTuple,
      ResolverSlashedEvent.OutputObject
    >;

    "ResolverTierUpgraded(address,uint8)": TypedContractEvent<
      ResolverTierUpgradedEvent.InputTuple,
      ResolverTierUpgradedEvent.OutputTuple,
      ResolverTierUpgradedEvent.OutputObject
    >;
    ResolverTierUpgraded: TypedContractEvent<
      ResolverTierUpgradedEvent.InputTuple,
      ResolverTierUpgradedEvent.OutputTuple,
      ResolverTierUpgradedEvent.OutputObject
    >;

    "ResolverUnstaked(address)": TypedContractEvent<
      ResolverUnstakedEvent.InputTuple,
      ResolverUnstakedEvent.OutputTuple,
      ResolverUnstakedEvent.OutputObject
    >;
    ResolverUnstaked: TypedContractEvent<
      ResolverUnstakedEvent.InputTuple,
      ResolverUnstakedEvent.OutputTuple,
      ResolverUnstakedEvent.OutputObject
    >;

    "RewardClaimed(address)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardEpochFunded(uint64)": TypedContractEvent<
      RewardEpochFundedEvent.InputTuple,
      RewardEpochFundedEvent.OutputTuple,
      RewardEpochFundedEvent.OutputObject
    >;
    RewardEpochFunded: TypedContractEvent<
      RewardEpochFundedEvent.InputTuple,
      RewardEpochFundedEvent.OutputTuple,
      RewardEpochFundedEvent.OutputObject
    >;

    "VoteCast(bytes32,address)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoteFinalized(bytes32,uint8)": TypedContractEvent<
      VoteFinalizedEvent.InputTuple,
      VoteFinalizedEvent.OutputTuple,
      VoteFinalizedEvent.OutputObject
    >;
    VoteFinalized: TypedContractEvent<
      VoteFinalizedEvent.InputTuple,
      VoteFinalizedEvent.OutputTuple,
      VoteFinalizedEvent.OutputObject
    >;
  };
}
