/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FhenixGovernance } from "./FhenixGovernance";
export type { IFhenixMarkets } from "./IFhenixMarkets";
