/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FhenixMarkets {
  export type MarketStruct = {
    id: BytesLike;
    creator: AddressLike;
    resolver: AddressLike;
    questionHash: BytesLike;
    category: BigNumberish;
    numOutcomes: BigNumberish;
    deadline: BigNumberish;
    resolutionDeadline: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
  };

  export type MarketStructOutput = [
    id: string,
    creator: string,
    resolver: string,
    questionHash: string,
    category: bigint,
    numOutcomes: bigint,
    deadline: bigint,
    resolutionDeadline: bigint,
    status: bigint,
    createdAt: bigint
  ] & {
    id: string;
    creator: string;
    resolver: string;
    questionHash: string;
    category: bigint;
    numOutcomes: bigint;
    deadline: bigint;
    resolutionDeadline: bigint;
    status: bigint;
    createdAt: bigint;
  };

  export type AMMPoolStruct = {
    reserve1: BigNumberish;
    reserve2: BigNumberish;
    reserve3: BigNumberish;
    reserve4: BigNumberish;
    totalLiquidity: BigNumberish;
    totalLPShares: BigNumberish;
    totalVolume: BigNumberish;
  };

  export type AMMPoolStructOutput = [
    reserve1: bigint,
    reserve2: bigint,
    reserve3: bigint,
    reserve4: bigint,
    totalLiquidity: bigint,
    totalLPShares: bigint,
    totalVolume: bigint
  ] & {
    reserve1: bigint;
    reserve2: bigint;
    reserve3: bigint;
    reserve4: bigint;
    totalLiquidity: bigint;
    totalLPShares: bigint;
    totalVolume: bigint;
  };

  export type VoteTallyStruct = {
    outcome1Bonds: BigNumberish;
    outcome2Bonds: BigNumberish;
    outcome3Bonds: BigNumberish;
    outcome4Bonds: BigNumberish;
    totalVoters: BigNumberish;
    totalBonded: BigNumberish;
    votingDeadline: BigNumberish;
    disputeDeadline: BigNumberish;
    finalized: boolean;
    winningOutcome: BigNumberish;
  };

  export type VoteTallyStructOutput = [
    outcome1Bonds: bigint,
    outcome2Bonds: bigint,
    outcome3Bonds: bigint,
    outcome4Bonds: bigint,
    totalVoters: bigint,
    totalBonded: bigint,
    votingDeadline: bigint,
    disputeDeadline: bigint,
    finalized: boolean,
    winningOutcome: bigint
  ] & {
    outcome1Bonds: bigint;
    outcome2Bonds: bigint;
    outcome3Bonds: bigint;
    outcome4Bonds: bigint;
    totalVoters: bigint;
    totalBonded: bigint;
    votingDeadline: bigint;
    disputeDeadline: bigint;
    finalized: boolean;
    winningOutcome: bigint;
  };
}

export interface FhenixMarketsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR_FEE_BPS"
      | "DISPUTE_BOND_MULTIPLIER"
      | "DISPUTE_WINDOW"
      | "FEE_DENOMINATOR"
      | "LP_FEE_BPS"
      | "MARKET_STATUS_ACTIVE"
      | "MARKET_STATUS_CANCELLED"
      | "MARKET_STATUS_CLOSED"
      | "MARKET_STATUS_RESOLVED"
      | "MIN_LIQUIDITY"
      | "MIN_TRADE_AMOUNT"
      | "MIN_VOTERS"
      | "MIN_VOTE_BOND"
      | "PROTOCOL_FEE_BPS"
      | "STATUS_DISPUTED"
      | "STATUS_PENDING_FINALIZATION"
      | "STATUS_PENDING_RESOLUTION"
      | "VOTER_REWARD_PERCENT"
      | "VOTE_WINDOW"
      | "WINNER_CLAIM_PRIORITY"
      | "addLiquidity"
      | "ammPools"
      | "approveTreasuryProposal"
      | "buyShares"
      | "cancelMarket"
      | "claimDisputeBond"
      | "claimLPRefund"
      | "claimRefund"
      | "claimVoterBond"
      | "claimVoterReward"
      | "closeMarket"
      | "confirmResolution"
      | "createMarket"
      | "deployer"
      | "disputeResolution"
      | "executeTreasuryProposal"
      | "finalizeVotes"
      | "getEncLPBalance"
      | "getEncShareBalance"
      | "getMarket"
      | "getPool"
      | "getPrices"
      | "getVoteTally"
      | "initMultisig"
      | "marketCount"
      | "marketCredits"
      | "marketFees"
      | "markets"
      | "multisig"
      | "multisigApprovals"
      | "proposeTreasuryWithdrawal"
      | "redeemShares"
      | "sellShares"
      | "treasuryProposals"
      | "voteOutcome"
      | "voteTallies"
      | "withdrawCreatorFees"
      | "withdrawLiquidity"
      | "withdrawProtocolFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "LiquidityWithdrawn"
      | "MarketCancelled"
      | "MarketClosed"
      | "MarketCreated"
      | "MultisigInitialized"
      | "RefundClaimed"
      | "ResolutionConfirmed"
      | "ResolutionDisputed"
      | "SharesBought"
      | "SharesRedeemed"
      | "SharesSold"
      | "TreasuryProposalApproved"
      | "TreasuryProposalCreated"
      | "TreasuryProposalExecuted"
      | "VoteSubmitted"
      | "VotesFinalized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CREATOR_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_BOND_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LP_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKET_STATUS_ACTIVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKET_STATUS_CANCELLED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKET_STATUS_CLOSED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKET_STATUS_RESOLVED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_TRADE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_DISPUTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_PENDING_FINALIZATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STATUS_PENDING_RESOLUTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTER_REWARD_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WINNER_CLAIM_PRIORITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "ammPools", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "approveTreasuryProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyShares",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDisputeBond",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimLPRefund",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimVoterBond",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimVoterReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmResolution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "disputeResolution",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTreasuryProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeVotes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncLPBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncShareBalance",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getPool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPrices",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteTally",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initMultisig",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketCredits",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketFees",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "multisig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multisigApprovals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeTreasuryWithdrawal",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemShares",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellShares",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryProposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOutcome",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteTallies",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCreatorFees",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLiquidity",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProtocolFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CREATOR_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_BOND_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LP_FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MARKET_STATUS_ACTIVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARKET_STATUS_CANCELLED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARKET_STATUS_CLOSED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARKET_STATUS_RESOLVED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_TRADE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_VOTERS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOTE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_DISPUTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_PENDING_FINALIZATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STATUS_PENDING_RESOLUTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTER_REWARD_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WINNER_CLAIM_PRIORITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ammPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveTreasuryProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDisputeBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimLPRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimVoterBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimVoterReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTreasuryProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncLPBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncShareBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVoteTally",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketFees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multisig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multisigApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeTreasuryWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteTallies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCreatorFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProtocolFees",
    data: BytesLike
  ): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [marketId: BytesLike, provider: AddressLike];
  export type OutputTuple = [marketId: string, provider: string];
  export interface OutputObject {
    marketId: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityWithdrawnEvent {
  export type InputTuple = [marketId: BytesLike, provider: AddressLike];
  export type OutputTuple = [marketId: string, provider: string];
  export interface OutputObject {
    marketId: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [marketId: BytesLike];
  export type OutputTuple = [marketId: string];
  export interface OutputObject {
    marketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketClosedEvent {
  export type InputTuple = [marketId: BytesLike];
  export type OutputTuple = [marketId: string];
  export interface OutputObject {
    marketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    creator: AddressLike,
    questionHash: BytesLike,
    numOutcomes: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    creator: string,
    questionHash: string,
    numOutcomes: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    marketId: string;
    creator: string;
    questionHash: string;
    numOutcomes: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigInitializedEvent {
  export type InputTuple = [
    signer1: AddressLike,
    signer2: AddressLike,
    signer3: AddressLike,
    threshold: BigNumberish
  ];
  export type OutputTuple = [
    signer1: string,
    signer2: string,
    signer3: string,
    threshold: bigint
  ];
  export interface OutputObject {
    signer1: string;
    signer2: string;
    signer3: string;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [marketId: BytesLike, claimer: AddressLike];
  export type OutputTuple = [marketId: string, claimer: string];
  export interface OutputObject {
    marketId: string;
    claimer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionConfirmedEvent {
  export type InputTuple = [marketId: BytesLike, winningOutcome: BigNumberish];
  export type OutputTuple = [marketId: string, winningOutcome: bigint];
  export interface OutputObject {
    marketId: string;
    winningOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionDisputedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    disputer: AddressLike,
    proposedOutcome: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    disputer: string,
    proposedOutcome: bigint
  ];
  export interface OutputObject {
    marketId: string;
    disputer: string;
    proposedOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesBoughtEvent {
  export type InputTuple = [marketId: BytesLike, buyer: AddressLike];
  export type OutputTuple = [marketId: string, buyer: string];
  export interface OutputObject {
    marketId: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesRedeemedEvent {
  export type InputTuple = [marketId: BytesLike, redeemer: AddressLike];
  export type OutputTuple = [marketId: string, redeemer: string];
  export interface OutputObject {
    marketId: string;
    redeemer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesSoldEvent {
  export type InputTuple = [marketId: BytesLike, seller: AddressLike];
  export type OutputTuple = [marketId: string, seller: string];
  export interface OutputObject {
    marketId: string;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryProposalApprovedEvent {
  export type InputTuple = [proposalId: BytesLike, signer: AddressLike];
  export type OutputTuple = [proposalId: string, signer: string];
  export interface OutputObject {
    proposalId: string;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryProposalExecutedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteSubmittedEvent {
  export type InputTuple = [marketId: BytesLike, voter: AddressLike];
  export type OutputTuple = [marketId: string, voter: string];
  export interface OutputObject {
    marketId: string;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotesFinalizedEvent {
  export type InputTuple = [marketId: BytesLike, winningOutcome: BigNumberish];
  export type OutputTuple = [marketId: string, winningOutcome: bigint];
  export interface OutputObject {
    marketId: string;
    winningOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FhenixMarkets extends BaseContract {
  connect(runner?: ContractRunner | null): FhenixMarkets;
  waitForDeployment(): Promise<this>;

  interface: FhenixMarketsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_BOND_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  LP_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MARKET_STATUS_ACTIVE: TypedContractMethod<[], [bigint], "view">;

  MARKET_STATUS_CANCELLED: TypedContractMethod<[], [bigint], "view">;

  MARKET_STATUS_CLOSED: TypedContractMethod<[], [bigint], "view">;

  MARKET_STATUS_RESOLVED: TypedContractMethod<[], [bigint], "view">;

  MIN_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  MIN_TRADE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTERS: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTE_BOND: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  STATUS_DISPUTED: TypedContractMethod<[], [bigint], "view">;

  STATUS_PENDING_FINALIZATION: TypedContractMethod<[], [bigint], "view">;

  STATUS_PENDING_RESOLUTION: TypedContractMethod<[], [bigint], "view">;

  VOTER_REWARD_PERCENT: TypedContractMethod<[], [bigint], "view">;

  VOTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  WINNER_CLAIM_PRIORITY: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<[marketId: BytesLike], [void], "payable">;

  ammPools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        reserve1: bigint;
        reserve2: bigint;
        reserve3: bigint;
        reserve4: bigint;
        totalLiquidity: bigint;
        totalLPShares: bigint;
        totalVolume: bigint;
      }
    ],
    "view"
  >;

  approveTreasuryProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  buyShares: TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish, minSharesOut: BigNumberish],
    [void],
    "payable"
  >;

  cancelMarket: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  claimDisputeBond: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  claimLPRefund: TypedContractMethod<
    [marketId: BytesLike, lpSharesToRefund: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish, sharesToRefund: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimVoterBond: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  claimVoterReward: TypedContractMethod<[], [void], "nonpayable">;

  closeMarket: TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;

  confirmResolution: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      questionHash: BytesLike,
      category: BigNumberish,
      numOutcomes: BigNumberish,
      deadline: BigNumberish,
      resolutionDeadline: BigNumberish,
      resolver: AddressLike
    ],
    [string],
    "payable"
  >;

  deployer: TypedContractMethod<[], [string], "view">;

  disputeResolution: TypedContractMethod<
    [marketId: BytesLike, proposedOutcome: BigNumberish],
    [void],
    "payable"
  >;

  executeTreasuryProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeVotes: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  getEncLPBalance: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  getEncShareBalance: TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [string],
    "view"
  >;

  getMarket: TypedContractMethod<
    [marketId: BytesLike],
    [FhenixMarkets.MarketStructOutput],
    "view"
  >;

  getPool: TypedContractMethod<
    [marketId: BytesLike],
    [FhenixMarkets.AMMPoolStructOutput],
    "view"
  >;

  getPrices: TypedContractMethod<
    [marketId: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price1: bigint;
        price2: bigint;
        price3: bigint;
        price4: bigint;
      }
    ],
    "view"
  >;

  getVoteTally: TypedContractMethod<
    [marketId: BytesLike],
    [FhenixMarkets.VoteTallyStructOutput],
    "view"
  >;

  initMultisig: TypedContractMethod<
    [signer1: AddressLike, signer2: AddressLike, signer3: AddressLike],
    [void],
    "nonpayable"
  >;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  marketCredits: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  marketFees: TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint] & { protocolFees: bigint; creatorFees: bigint }],
    "view"
  >;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        creator: string;
        resolver: string;
        questionHash: string;
        category: bigint;
        numOutcomes: bigint;
        deadline: bigint;
        resolutionDeadline: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  multisig: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, boolean] & {
        signer1: string;
        signer2: string;
        signer3: string;
        threshold: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  multisigApprovals: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  proposeTreasuryWithdrawal: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  redeemShares: TypedContractMethod<
    [marketId: BytesLike, sharesToRedeem: BigNumberish],
    [void],
    "nonpayable"
  >;

  sellShares: TypedContractMethod<
    [
      marketId: BytesLike,
      outcome: BigNumberish,
      sharesToSell: BigNumberish,
      minTokensOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  treasuryProposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, bigint] & {
        id: string;
        proposer: string;
        recipient: string;
        amount: bigint;
        approvals: bigint;
        executed: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  voteOutcome: TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [void],
    "payable"
  >;

  voteTallies: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        outcome1Bonds: bigint;
        outcome2Bonds: bigint;
        outcome3Bonds: bigint;
        outcome4Bonds: bigint;
        totalVoters: bigint;
        totalBonded: bigint;
        votingDeadline: bigint;
        disputeDeadline: bigint;
        finalized: boolean;
        winningOutcome: bigint;
      }
    ],
    "view"
  >;

  withdrawCreatorFees: TypedContractMethod<
    [marketId: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawLiquidity: TypedContractMethod<
    [marketId: BytesLike, lpSharesToWithdraw: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawProtocolFees: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_BOND_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LP_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MARKET_STATUS_ACTIVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MARKET_STATUS_CANCELLED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MARKET_STATUS_CLOSED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MARKET_STATUS_RESOLVED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TRADE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_DISPUTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_PENDING_FINALIZATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STATUS_PENDING_RESOLUTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTER_REWARD_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WINNER_CLAIM_PRIORITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<[marketId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "ammPools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        reserve1: bigint;
        reserve2: bigint;
        reserve3: bigint;
        reserve4: bigint;
        totalLiquidity: bigint;
        totalLPShares: bigint;
        totalVolume: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveTreasuryProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buyShares"
  ): TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish, minSharesOut: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDisputeBond"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimLPRefund"
  ): TypedContractMethod<
    [marketId: BytesLike, lpSharesToRefund: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish, sharesToRefund: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimVoterBond"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimVoterReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeMarket"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmResolution"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      questionHash: BytesLike,
      category: BigNumberish,
      numOutcomes: BigNumberish,
      deadline: BigNumberish,
      resolutionDeadline: BigNumberish,
      resolver: AddressLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deployer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputeResolution"
  ): TypedContractMethod<
    [marketId: BytesLike, proposedOutcome: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeTreasuryProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeVotes"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncLPBalance"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncShareBalance"
  ): TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [FhenixMarkets.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [FhenixMarkets.AMMPoolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrices"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price1: bigint;
        price2: bigint;
        price3: bigint;
        price4: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoteTally"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [FhenixMarkets.VoteTallyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initMultisig"
  ): TypedContractMethod<
    [signer1: AddressLike, signer2: AddressLike, signer3: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketCredits"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketFees"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint] & { protocolFees: bigint; creatorFees: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        creator: string;
        resolver: string;
        questionHash: string;
        category: bigint;
        numOutcomes: bigint;
        deadline: bigint;
        resolutionDeadline: bigint;
        status: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "multisig"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, boolean] & {
        signer1: string;
        signer2: string;
        signer3: string;
        threshold: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "multisigApprovals"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposeTreasuryWithdrawal"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemShares"
  ): TypedContractMethod<
    [marketId: BytesLike, sharesToRedeem: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellShares"
  ): TypedContractMethod<
    [
      marketId: BytesLike,
      outcome: BigNumberish,
      sharesToSell: BigNumberish,
      minTokensOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "treasuryProposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, bigint] & {
        id: string;
        proposer: string;
        recipient: string;
        amount: bigint;
        approvals: bigint;
        executed: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteOutcome"
  ): TypedContractMethod<
    [marketId: BytesLike, outcome: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "voteTallies"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        outcome1Bonds: bigint;
        outcome2Bonds: bigint;
        outcome3Bonds: bigint;
        outcome4Bonds: bigint;
        totalVoters: bigint;
        totalBonded: bigint;
        votingDeadline: bigint;
        disputeDeadline: bigint;
        finalized: boolean;
        winningOutcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawCreatorFees"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<
    [marketId: BytesLike, lpSharesToWithdraw: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawProtocolFees"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityWithdrawn"
  ): TypedContractEvent<
    LiquidityWithdrawnEvent.InputTuple,
    LiquidityWithdrawnEvent.OutputTuple,
    LiquidityWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketClosed"
  ): TypedContractEvent<
    MarketClosedEvent.InputTuple,
    MarketClosedEvent.OutputTuple,
    MarketClosedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MultisigInitialized"
  ): TypedContractEvent<
    MultisigInitializedEvent.InputTuple,
    MultisigInitializedEvent.OutputTuple,
    MultisigInitializedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionConfirmed"
  ): TypedContractEvent<
    ResolutionConfirmedEvent.InputTuple,
    ResolutionConfirmedEvent.OutputTuple,
    ResolutionConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionDisputed"
  ): TypedContractEvent<
    ResolutionDisputedEvent.InputTuple,
    ResolutionDisputedEvent.OutputTuple,
    ResolutionDisputedEvent.OutputObject
  >;
  getEvent(
    key: "SharesBought"
  ): TypedContractEvent<
    SharesBoughtEvent.InputTuple,
    SharesBoughtEvent.OutputTuple,
    SharesBoughtEvent.OutputObject
  >;
  getEvent(
    key: "SharesRedeemed"
  ): TypedContractEvent<
    SharesRedeemedEvent.InputTuple,
    SharesRedeemedEvent.OutputTuple,
    SharesRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "SharesSold"
  ): TypedContractEvent<
    SharesSoldEvent.InputTuple,
    SharesSoldEvent.OutputTuple,
    SharesSoldEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryProposalApproved"
  ): TypedContractEvent<
    TreasuryProposalApprovedEvent.InputTuple,
    TreasuryProposalApprovedEvent.OutputTuple,
    TreasuryProposalApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryProposalCreated"
  ): TypedContractEvent<
    TreasuryProposalCreatedEvent.InputTuple,
    TreasuryProposalCreatedEvent.OutputTuple,
    TreasuryProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryProposalExecuted"
  ): TypedContractEvent<
    TreasuryProposalExecutedEvent.InputTuple,
    TreasuryProposalExecutedEvent.OutputTuple,
    TreasuryProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VoteSubmitted"
  ): TypedContractEvent<
    VoteSubmittedEvent.InputTuple,
    VoteSubmittedEvent.OutputTuple,
    VoteSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "VotesFinalized"
  ): TypedContractEvent<
    VotesFinalizedEvent.InputTuple,
    VotesFinalizedEvent.OutputTuple,
    VotesFinalizedEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(bytes32,address)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityWithdrawn(bytes32,address)": TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;
    LiquidityWithdrawn: TypedContractEvent<
      LiquidityWithdrawnEvent.InputTuple,
      LiquidityWithdrawnEvent.OutputTuple,
      LiquidityWithdrawnEvent.OutputObject
    >;

    "MarketCancelled(bytes32)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketClosed(bytes32)": TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;
    MarketClosed: TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;

    "MarketCreated(bytes32,address,bytes32,uint8,uint64)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MultisigInitialized(address,address,address,uint8)": TypedContractEvent<
      MultisigInitializedEvent.InputTuple,
      MultisigInitializedEvent.OutputTuple,
      MultisigInitializedEvent.OutputObject
    >;
    MultisigInitialized: TypedContractEvent<
      MultisigInitializedEvent.InputTuple,
      MultisigInitializedEvent.OutputTuple,
      MultisigInitializedEvent.OutputObject
    >;

    "RefundClaimed(bytes32,address)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "ResolutionConfirmed(bytes32,uint8)": TypedContractEvent<
      ResolutionConfirmedEvent.InputTuple,
      ResolutionConfirmedEvent.OutputTuple,
      ResolutionConfirmedEvent.OutputObject
    >;
    ResolutionConfirmed: TypedContractEvent<
      ResolutionConfirmedEvent.InputTuple,
      ResolutionConfirmedEvent.OutputTuple,
      ResolutionConfirmedEvent.OutputObject
    >;

    "ResolutionDisputed(bytes32,address,uint8)": TypedContractEvent<
      ResolutionDisputedEvent.InputTuple,
      ResolutionDisputedEvent.OutputTuple,
      ResolutionDisputedEvent.OutputObject
    >;
    ResolutionDisputed: TypedContractEvent<
      ResolutionDisputedEvent.InputTuple,
      ResolutionDisputedEvent.OutputTuple,
      ResolutionDisputedEvent.OutputObject
    >;

    "SharesBought(bytes32,address)": TypedContractEvent<
      SharesBoughtEvent.InputTuple,
      SharesBoughtEvent.OutputTuple,
      SharesBoughtEvent.OutputObject
    >;
    SharesBought: TypedContractEvent<
      SharesBoughtEvent.InputTuple,
      SharesBoughtEvent.OutputTuple,
      SharesBoughtEvent.OutputObject
    >;

    "SharesRedeemed(bytes32,address)": TypedContractEvent<
      SharesRedeemedEvent.InputTuple,
      SharesRedeemedEvent.OutputTuple,
      SharesRedeemedEvent.OutputObject
    >;
    SharesRedeemed: TypedContractEvent<
      SharesRedeemedEvent.InputTuple,
      SharesRedeemedEvent.OutputTuple,
      SharesRedeemedEvent.OutputObject
    >;

    "SharesSold(bytes32,address)": TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;
    SharesSold: TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;

    "TreasuryProposalApproved(bytes32,address)": TypedContractEvent<
      TreasuryProposalApprovedEvent.InputTuple,
      TreasuryProposalApprovedEvent.OutputTuple,
      TreasuryProposalApprovedEvent.OutputObject
    >;
    TreasuryProposalApproved: TypedContractEvent<
      TreasuryProposalApprovedEvent.InputTuple,
      TreasuryProposalApprovedEvent.OutputTuple,
      TreasuryProposalApprovedEvent.OutputObject
    >;

    "TreasuryProposalCreated(bytes32,address,uint128)": TypedContractEvent<
      TreasuryProposalCreatedEvent.InputTuple,
      TreasuryProposalCreatedEvent.OutputTuple,
      TreasuryProposalCreatedEvent.OutputObject
    >;
    TreasuryProposalCreated: TypedContractEvent<
      TreasuryProposalCreatedEvent.InputTuple,
      TreasuryProposalCreatedEvent.OutputTuple,
      TreasuryProposalCreatedEvent.OutputObject
    >;

    "TreasuryProposalExecuted(bytes32,address,uint128)": TypedContractEvent<
      TreasuryProposalExecutedEvent.InputTuple,
      TreasuryProposalExecutedEvent.OutputTuple,
      TreasuryProposalExecutedEvent.OutputObject
    >;
    TreasuryProposalExecuted: TypedContractEvent<
      TreasuryProposalExecutedEvent.InputTuple,
      TreasuryProposalExecutedEvent.OutputTuple,
      TreasuryProposalExecutedEvent.OutputObject
    >;

    "VoteSubmitted(bytes32,address)": TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;
    VoteSubmitted: TypedContractEvent<
      VoteSubmittedEvent.InputTuple,
      VoteSubmittedEvent.OutputTuple,
      VoteSubmittedEvent.OutputObject
    >;

    "VotesFinalized(bytes32,uint8)": TypedContractEvent<
      VotesFinalizedEvent.InputTuple,
      VotesFinalizedEvent.OutputTuple,
      VotesFinalizedEvent.OutputObject
    >;
    VotesFinalized: TypedContractEvent<
      VotesFinalizedEvent.InputTuple,
      VotesFinalizedEvent.OutputTuple,
      VotesFinalizedEvent.OutputObject
    >;
  };
}
