/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fhenixGovernanceSol from "./FhenixGovernance.sol";
export type { fhenixGovernanceSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { FhenixMarkets } from "./FhenixMarkets";
