/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFhenixMarkets,
  IFhenixMarketsInterface,
} from "../../../contracts/FhenixGovernance.sol/IFhenixMarkets";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "marketId",
        type: "bytes32",
      },
    ],
    name: "markets",
    outputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "address",
        name: "resolver",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "questionHash",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "category",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "numOutcomes",
        type: "uint8",
      },
      {
        internalType: "uint64",
        name: "deadline",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "resolutionDeadline",
        type: "uint64",
      },
      {
        internalType: "uint8",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "uint64",
        name: "createdAt",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFhenixMarkets__factory {
  static readonly abi = _abi;
  static createInterface(): IFhenixMarketsInterface {
    return new Interface(_abi) as IFhenixMarketsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFhenixMarkets {
    return new Contract(address, _abi, runner) as unknown as IFhenixMarkets;
  }
}
