/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FhenixGovernance__factory } from "./FhenixGovernance__factory";
export { IFhenixMarkets__factory } from "./IFhenixMarkets__factory";
