/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fheSol from "./FHE.sol";
export type { fheSol };
import type * as iCofheSol from "./ICofhe.sol";
export type { iCofheSol };
