/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fhenixGovernanceSol from "./FhenixGovernance.sol";
export * as mocks from "./mocks";
export { FhenixMarkets__factory } from "./FhenixMarkets__factory";
